spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/project?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: wether
    password: 1234
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

openWeather:
  apikey: 6d492a359c30de7a7895a7ad38017a05
  url: https://api.openweathermap.org/data/2.5/weather?q=seoul&appid=

logging:
  config: classpath:logback-spring.xml